# Generated by Django 3.2.10 on 2022-01-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_special',
        ),
    ]
