# Generated by Django 3.2.5 on 2021-07-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tut', '0003_auto_20210729_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='tut.Category', verbose_name='دسته بندی'),
        ),
    ]
