# Generated by Django 3.2.5 on 2021-09-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tut', '0004_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='tut.Category', verbose_name='دسته بندی'),
        ),
    ]
