# Generated by Django 3.2.10 on 2022-04-23 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tut', '0011_auto_20220412_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
